# Generated by Django 4.2.5 on 2023-11-30 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCate', models.AutoField(primary_key=True, serialize=False)),
                ('nombreCate', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('idCiudad', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('nombreCiudad', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('idComuna', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('nombreComuna', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='controlGestor',
            fields=[
                ('idControl', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('fechaVencimiento', models.DateField()),
                ('fechaEntrada', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('idEmpresa', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('nombreEmpresa', models.CharField(max_length=25)),
                ('CantidadSucursal', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='EntradaProducto',
            fields=[
                ('idEntrada', models.AutoField(max_length=3, primary_key=True, serialize=False)),
                ('rutPersona', models.CharField(max_length=10)),
                ('fechaEntrada', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('rutPersona', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombreperso', models.CharField(max_length=25)),
                ('apellidoPerso', models.CharField(max_length=25)),
                ('fechaNacimiento', models.DateField()),
                ('idUser', models.IntegerField()),
                ('rangoUser', models.IntegerField()),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('idProduc', models.AutoField(max_length=5, primary_key=True, serialize=False)),
                ('nombreProduc', models.CharField(max_length=25)),
                ('cantidadProducto', models.IntegerField()),
                ('activo', models.BooleanField(default=True)),
                ('Detalle', models.TextField(blank=True, max_length=500, null=True)),
                ('cate', models.CharField(max_length=50)),
                ('subcate', models.CharField(max_length=50)),
                ('product_pila', models.CharField(max_length=50)),
                ('product_fecha', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ProductosdeFecha',
            fields=[
                ('idProducFecha', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fechaElavoracionP', models.DateField()),
                ('fechaVencimientoP', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='ProductosdePila',
            fields=[
                ('idPila', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('ControlPila', models.IntegerField(max_length=6)),
                ('PesoPila', models.IntegerField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('idRegion', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('nombreRegion', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='SalidaProducto',
            fields=[
                ('idSalidaProduct', models.AutoField(max_length=3, primary_key=True, serialize=False)),
                ('rutPersona', models.CharField(max_length=10)),
                ('fechaSalida', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SubCategoria',
            fields=[
                ('idSubCate', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('nombreSubCate', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('idSucursal', models.IntegerField(max_length=3, primary_key=True, serialize=False)),
                ('nombreSucursal', models.CharField(max_length=25)),
                ('Direccion', models.CharField(max_length=25)),
                ('tipoProducto', models.CharField(max_length=25)),
            ],
        ),
    ]
