# Generated by Django 4.2.5 on 2023-11-30 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ges', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='product_fecha',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='product_pila',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
