# Generated by Django 4.2.5 on 2023-12-03 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ges', '0002_alter_producto_product_fecha_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Persona',
        ),
    ]
