# Generated by Django 4.2.5 on 2023-12-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ges', '0003_delete_persona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudad',
            name='idCiudad',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='comuna',
            name='idComuna',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='controlgestor',
            name='idControl',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='idEmpresa',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='entradaproducto',
            name='idEntrada',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='producto',
            name='idProduc',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='productosdepila',
            name='ControlPila',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productosdepila',
            name='PesoPila',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='region',
            name='idRegion',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salidaproducto',
            name='idSalidaProduct',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='sucursal',
            name='idSucursal',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
