# Generated by Django 4.2.5 on 2023-12-04 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ges', '0004_alter_ciudad_idciudad_alter_comuna_idcomuna_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entradaproducto',
            name='rutPersona',
        ),
        migrations.RemoveField(
            model_name='salidaproducto',
            name='rutPersona',
        ),
    ]
